Repository prgrms-fe-devcourse/FEDC5_looky_heejin, pull requests merged in 2024-01, with the labels that each got.

#30 Update issue&PR templates
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#31 Feature/issue-template to dev
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#29 Feature/login-0.2.0
  src/pages/LoginPage/LoginPage.const.ts
  src/pages/LoginPage/LoginPage.styles.ts
  src/pages/LoginPage/LoginPageView.tsx
Labels: Refactor, Design

#33 Feature/Avatar 0.2.0
  src/assets/profile.svg
  src/components/common/Avatar/index.tsx
Labels: Refactor

#35 Feature/route 2.1.0
  src/App.tsx
  src/components/common/Navigator/BottomNavBar.tsx
  src/constants/queryKey.ts
  src/hooks/useAuth.ts
  src/hooks/useEventQuery.ts
  src/routes/AuthRoute.tsx
  src/routes/index.tsx
Labels: Fix

#38 Feature/avatar 0.2.1
  src/components/common/Avatar/index.tsx
Labels: Bug

#34 Feature/TopNavBar-0.1.0
  src/components/common/Icon/Icon.tsx
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/components/common/Navigator/TopNavBar/Elements/BackButton.tsx
  src/components/common/Navigator/TopNavBar/Elements/ChatAvatars.tsx
  src/components/common/Navigator/TopNavBar/Elements/ChatNotificationIconsBox.tsx
  src/components/common/Navigator/TopNavBar/Elements/LogoImage.tsx
  src/components/common/Navigator/TopNavBar/Elements/PageTitle.tsx
  src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
  src/components/common/Navigator/TopNavBar/index.ts
  src/constants/pathNameConstants.ts
  src/constants/uiConstants.ts
  src/hooks/useSearchValue.ts
  src/pages/NotificationsPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/store/reducers/index.ts
  src/store/reducers/searchReducer.ts
  src/styles/GlobalStyle.tsx
Labels: Feature

#39 Feature/bottom nav bar 0.1.1
  src/components/common/Layout/Layout.tsx
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/styles/GlobalStyle.tsx
Labels: Bug, Fix

#36 Feature/search page 0.1.0
  src/api/queries/search.ts
  src/components/SearchTab/index.tsx
  src/pages/SearchPage/SearchBar.tsx
  src/pages/SearchPage/SearchPage.const.ts
  src/pages/SearchPage/SearchPage.styles.ts
  src/pages/SearchPage/Views/SearchPostsView.tsx
  src/pages/SearchPage/Views/SearchRecentView.tsx
  src/pages/SearchPage/Views/SearchResultsView.tsx
  src/pages/SearchPage/Views/SearchUsersView.tsx
  src/pages/SearchPage/Views/index.ts
  src/pages/SearchPage/index.tsx
  src/types/index.ts
Labels: Feature

#37 Feature/CreatePostPage 0.4.0
  src/components/common/Button/Button.tsx
  src/components/common/Upload/Upload.tsx
  src/pages/CreatePostPage/CreatePostPage.view.tsx
Labels: Fix

#40 Feature/bottom nav bar 0.2.0
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/constants/icons.ts
  src/constants/pathNameConstants.ts
Labels: Fix

#41 Feature/notification page 0.1.0
  src/App.tsx
  src/components/Notification/NotificationCard/NotificationCard.styles.ts
  src/components/Notification/NotificationCard/NotificationCard.tsx
  src/components/Notification/NotificationCard/index.ts
  src/components/Notification/NotificationManager.tsx
  src/components/Notification/index.ts
  src/components/common/Image/index.tsx
  src/components/common/Layout/Layout.tsx
  src/hooks/useNotification.ts
  src/pages/NotificationsPage/NotificationsPage.styles.ts
  src/pages/NotificationsPage/NotificationsPage.view.tsx
  src/pages/NotificationsPage/index.ts
  src/pages/NotificationsPage/index.tsx
  src/routes/index.tsx
  src/store/reducers/index.ts
  src/store/reducers/notificationReducer.ts
  src/types/message.ts
  src/types/notification.ts
  src/types/post.ts
  src/types/user.ts
  src/utils/parseDate.ts
Labels: Feature

#43 Feature/splash-page-0.2.0
  src/pages/SplashPage/SplashPage.style.ts
  src/pages/SplashPage/index.tsx
Labels: Feature, Refactor

#45 Feature/signIn-0.2.2
  src/pages/SignInPage/SignInPage.const.ts
  src/pages/SignInPage/SignInPage.styles.ts
  src/pages/SignInPage/SignInPageView.tsx
Labels: Refactor, Fix, Design

#44 Feature/login-0.2.1
  src/components/common/ToolTip/ToolTip.tsx
  src/components/common/ToolTip/index.ts
  src/components/common/index.ts
  src/pages/LoginPage/LoginPage.const.ts
  src/pages/LoginPage/LoginPage.styles.ts
  src/pages/LoginPage/LoginPageView.tsx
Labels: Refactor, Design

#46 Feature/TopNavBar-0.2.0
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
Labels: Fix

#48 Feature/chat 0.1.0
  src/components/Chats/ChatLi/ChatLi.styles.ts
  src/components/Chats/ChatLi/ChatLi.tsx
  src/components/Chats/ChatLi/index.ts
  src/components/Chats/Message/Message.styles.ts
  src/components/Chats/Message/Message.tsx
  src/components/Chats/Message/index.ts
  src/components/Chats/index.ts
  src/components/common/EllipsisText/EllipsisText.tsx
  src/components/common/EllipsisText/index.ts
  src/components/common/Input/Input.tsx
  src/components/common/index.ts
  src/constants/queryKey.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatPage/index.ts
  src/pages/ChatPage/index.tsx
  src/pages/ChatsPage/ChatsPage.tsx
  src/pages/ChatsPage/index.ts
  src/pages/ChatsPage/index.tsx
  src/routes/index.tsx
  src/styles/theme.ts
  src/types/message.ts
  src/utils/parseDate.ts
Labels: Feature

#42 Feature/post-simple-card-0.1.0
  src/api/index.ts
  src/api/queries/userData.ts
  src/components/common/PostSimpleCard/PostSimpleCard.const.ts
  src/components/common/PostSimpleCard/PostSimpleCard.hook.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.styles.ts
  src/components/common/PostSimpleCard/PostSimpleCard.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.type.ts
  src/components/common/PostSimpleCard/PostSimpleCard.util.ts
  src/components/common/PostSimpleCard/index.tsx
Labels: Feature

#51 Feature/channelpage-0.1.0
  src/pages/ChannelsPage/ChannelsPage.styles.ts
  src/pages/ChannelsPage/ChannelsPage.view.tsx
  src/pages/ChannelsPage/index.tsx
Labels: Feature

#50 Style/style refactoring
  src/components/common/Button/Button.styles.ts
  src/components/common/Modal/Modal.styles.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ModalLayout.tsx
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
  src/components/common/Upload/Upload.tsx
  src/constants/uiConstants.ts
  src/pages/CreatePostPage/CreatePostPage.styles.ts
  src/pages/CreatePostPage/CreatePostPage.view.tsx
Labels: Design

#53 Feature/homepage-0.1.0 와 연관된 기능 일부
  src/api/queries/channelPosts.ts
  src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.styles.ts
  src/components/common/PostSimpleCard/PostSimpleCard.tsx
  src/pages/ChannelsPage/ChannelsPage.view.tsx
  src/pages/HomePage/HomePage.const.ts
  src/pages/HomePage/HomePage.hook.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomePage.type.ts
  src/pages/HomePage/HomePage.util.ts
  src/pages/HomePage/index.tsx
  src/pages/SplashPage/index.tsx
Labels: Feature, Fix, Design

#55 Style/style refactoring
  src/App.tsx
  src/components/Chats/ChatLi/ChatLi.tsx
  src/components/Chats/Message/Message.tsx
  src/components/common/InputLabel/InputLabel.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
  src/hooks/useNotification.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatsPage/ChatsPage.tsx
  src/pages/NotificationsPage/NotificationsPage.view.tsx
  src/store/reducers/notificationReducer.ts
  src/styles/GlobalStyle.tsx
Labels: Fix, Design

#56 Feature/top-nav-bar-0.2.1
  src/components/common/Navigator/TopNavBar/Elements/ChatAvatars.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
Labels: Fix

#57 Feature/profile page 0.1.1
  public/image_alt.png
  public/profile.png
  src/api/queries/profile.ts
  src/assets/image_alt.png
  src/assets/profile.png
  src/assets/profile.svg
  src/components/ButtonSet/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.tsx
  src/components/common/uiContext.tsx
  src/components/index.ts
  src/components/modalViews/ProfileModal/ChangeImageModal.tsx
  src/components/modalViews/ProfileModal/EditNameModal.tsx
  src/components/modalViews/ProfileModal/EditPasswordModal.tsx
  src/components/modalViews/ProfileModal/ProfileModal.style.ts
  src/components/modalViews/index.ts
  src/constants/queryKey.ts
  src/hooks/useProfile.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/ProfilePage/ProfilePage.const.ts
  src/pages/ProfilePage/ProfilePage.style.tsx
  src/pages/ProfilePage/Views/ProfilePostsView.tsx
  src/pages/ProfilePage/Views/ProfileView.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/SearchPage/index.tsx
  src/store/reducers/index.ts
  src/store/reducers/profileReducer.ts
  src/store/types/modalType.ts
  src/types/index.ts
  src/types/profile.ts
Labels: Feature, Fix, Design

#58 Feature/notification page 2.2.0
  src/components/Notification/NotificationCard/NotificationCard.tsx
  src/pages/NotificationsPage/NotificationsPage.view.tsx
Labels: Fix

#60 Feature/profile page 0.2.0
  src/pages/ProfilePage/Views/ProfileView.tsx
Labels: HotFix

#61 feature/Route-3.1.0
  package-lock.json
  package.json
  src/components/common/Layout/Layout.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/SearchPage/SearchPage.styles.ts
  src/routes/Transition.tsx
  src/routes/index.tsx
  src/styles/GlobalStyle.tsx
Labels: Fix, Design

#65 Feature/managed UI 1.1.0
  src/components/common/Button/Button.tsx
  src/components/common/uiContext.tsx
  src/components/modalViews/ChannelSelectModal.tsx
  src/components/modalViews/TagCreateModal.tsx
  src/hooks/useNewPost.ts
  src/pages/CreatePostPage/CreatePostPage.view.tsx
  src/routes/index.tsx
  src/store/reducers/index.ts
  src/store/reducers/modalReducer.ts
  src/store/reducers/newPostReducer.ts
  src/store/types/newPostType.ts
Labels: Refactor

#66 Feature/toastify
  package-lock.json
  package.json
  src/components/common/Navigator/TopNavBar/Elements/ChatNotificationIconsBox.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.styles.ts
  src/components/common/PostSimpleCard/PostSimpleCard.tsx
  src/pages/CreatePostPage/CreatePostPage.view.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/LoginPage/LoginPageView.tsx
  src/pages/SignInPage/SignInPageView.tsx
  src/routes/index.tsx
  src/styles/theme.ts
  src/utils/toast.tsx
Labels: Feature, Refactor, Design

#74 fix: 알림 카운트 처리 오류 수정
  src/store/reducers/notificationReducer.ts
Labels: Fix

#67 Feature/post detail-0.2.0
  public/looky_spinner.png
  src/components/common/Spinner/Spinner.tsx
  src/components/common/Spinner/index.ts
  src/components/modalViews/PostDetailModal/Comments/Comment.tsx
  src/components/modalViews/PostDetailModal/PostDetailModal.styles.ts
  src/components/modalViews/PostDetailModal/PostDetailModal.tsx
  src/constants/icons.ts
  src/constants/uiConstants.ts
  src/types/index.ts
Labels: Fix

#68 Featrue/search page 0.2.1
  src/components/SearchTab/index.tsx
  src/pages/SearchPage/SearchBar.tsx
  src/pages/SearchPage/SearchPage.const.ts
  src/pages/SearchPage/SearchPage.styles.ts
  src/pages/SearchPage/Views/SearchEmptyView.tsx
  src/pages/SearchPage/Views/SearchPostsView.tsx
  src/pages/SearchPage/Views/SearchRecentView.tsx
  src/pages/SearchPage/Views/SearchResultsView.tsx
  src/pages/SearchPage/Views/SearchUsersView.tsx
  src/pages/SearchPage/Views/index.ts
  src/pages/SearchPage/index.tsx
Labels: Refactor, Fix, Design

#70 Feature/admin-0.1.0
  src/api/queries/createChannel.ts
  src/components/Admin/Admin.tsx
  src/components/Admin/index.tsx
  src/components/common/PostSimpleCard/PostSimpleCard.tsx
  src/components/common/uiContext.tsx
  src/components/modalViews/ChannelCreateModal.tsx
  src/components/modalViews/ProfileModal/ChangeImageModal.tsx
  src/components/modalViews/ProfileModal/EditNameModal.tsx
  src/components/modalViews/index.ts
  src/pages/HomePage/HomePage.tsx
  src/store/types/modalType.ts
  src/types/channel.ts
Labels: Feature

#72 docs: Readme 내용 업데이트
  README.md
Labels: Chore

#71 feature/channelPage-0.1.1
  src/pages/ChannelsPage/ChannelsPage.styles.ts
  src/pages/ChannelsPage/ChannelsPage.view.tsx
Labels: Fix, Design

#73 Feature/profile page 0.2.1
  src/components/modalViews/ProfileModal/ChangeImageModal.tsx
  src/components/modalViews/ProfileModal/EditNameModal.tsx
  src/components/modalViews/ProfileModal/EditPasswordModal.tsx
  src/pages/ProfilePage/Views/ProfilePostsView.tsx
  src/pages/ProfilePage/Views/ProfileView.tsx
  src/pages/ProfilePage/index.tsx
Labels: Refactor, Fix

#79 feature/ProfilePage-0.2.2
  src/components/modalViews/ProfileModal/ChangeImageModal.tsx
Labels: Fix

#81 Feature/TopNavBar-0.2.3
  src/components/common/Navigator/TopNavBar/Elements/ChatAvatars.tsx
  src/components/common/Navigator/TopNavBar/TopNavBar.tsx
Labels: Feature, Fix
